### ISSUE TITLE
Eslint and prettier

### ISSUE THREAD

**Issue by tshemsedinov** [gapiyka/hermit#4]
You need eslint and prettier with default config to fix code style after them

**Comment by gapiyka** [comment]
Hi  there @tshemsedinov ✋🏿
If I'm not mistaken, in last commit [`prettier commit`](https://github.com/gapiyka/hermit/commit/8dc3e35a6112d42385e569148ec82cfc6ff31ac4) i added prettier extension with default settings configurations(but also switch on a func: `indent lines with tabs` ) and run all code through it 🛠 


**eslint was installed from the start of project

**Comment by tshemsedinov** [comment]
eslint and prettier are not an extension for your IDE, they are dependencies, you need `package.json`, `.prettierrc`, `.eslintrc.json`, see example: https://github.com/metarhia/metacom

**Comment by tshemsedinov** [comment]
code style doesn't looks like after default config

**Comment by gapiyka** [comment]
bruh

I tried to do what u suggest -___-
Is it correct now? Check in new one [`commit`](https://github.com/gapiyka/hermit/commit/34a68330035b32ed929d41e2fd8d68c5d102c62a).
* initialize package.json
* add  `package.json`, `.prettierrc`, `.eslintrc.json` files
* change config on default from metarhia rep.

![image](https://media1.tenor.com/images/18143f7895b22b936cc5b1d743f45599/tenor.gif?itemid=19746510)

**Comment by tshemsedinov** [comment]
Improve code style where possible
- You still have multiple magic numbers
- Use collections instead of switch/case (and if/else blocks)
- Avoid code duplication, create abstractions (classes, functions)
- Fix naming

**Comment by gapiyka** [comment]
👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧
Remade in those two commits:
* [naming+decompose+less magic number](https://github.com/gapiyka/hermit/commit/c25aa2cb0795a46b2d64dc2f1c4094795d6bfe82)
* [remove switch/case](https://github.com/gapiyka/hermit/commit/f08dfa245f639afeb63660076b625763e7e734fa)


👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧
