### ISSUE TITLE
Decompose long procedures

### ISSUE THREAD

**Issue by tshemsedinov** [gapiyka/hermit#5]
Like this https://github.com/gapiyka/hermit/blob/main/js/game.js#L536-L671

**Comment by gapiyka** [comment]
👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧
Remade in [prev-commit](https://github.com/gapiyka/hermit/commit/c25aa2cb0795a46b2d64dc2f1c4094795d6bfe82)
👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧👨🏻‍🔧
